# Database credentials
database:
  # antingen denna
  file: "database/db.sqlite" 
  # eller alla dessa (om file är blankt)
  sql-user: ""
  sql-pass: ""
  sql-server: "127.0.0.1"
  sql-database: "SupportSystem"
  sql-port: 3306

redis:
  server: "localhost:6379"

sso:
  clientId:  ""
  clientSecret:  ""
  baseAddress:  "https://localhost:44375/"
  backBaseAddress: "https://localhost:8080/"


